version: '3'

services:
    postgres:
        container_name: postgres
        image: postgres:12.6-alpine
        environment:
            - POSTGRES_USER=vectorai
            - POSTGRES_PASSWORD=vectorai
            - POSTGRES_DB=vectorai
            - PGDATA=/var/lib/postgres/data
            - TZ=GMT+5:30
            - PGTZ=GMT+5:30
        volumes:
            - postgres:/var/lib/postgres/data
        ports:
            - 5433:5432
        networks:
            - vectorai-network
    
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - 8001:80
        networks:
            - vectorai-network
        depends_on: 
            - postgres
        restart: unless-stopped

    api:
        container_name: fastapi-service
        build:
            dockerfile: Dockerfile
            context: ./api
        volumes:
            - ./api:/usr/src/api
        ports:
            - 8000:8000
        depends_on: 
            - postgres
            - pgadmin
        networks: 
            - vectorai-network
    
    client:
        container_name: react-client
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        build:
            dockerfile: Dockerfile
            context: ./client
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - ./client:/app
        networks:
            - vectorai-network

networks:
    vectorai-network:
        driver: bridge

volumes:
    postgres:
    pgadmin: